### ISSUE TITLE
Expose last move played to CPU players (explicitly)

### ISSUE THREAD

**Issue by maksverver** [ElTh0r0/stackandconquer#9]
As discussed on pull request #8: the game rules disallow undoing the last move played, but currently the CPU isn't explicitly told what the last move was. It can only be inferred from the `legalMoves` array. It would be more convenient if this bit of information was passed to `callCPU()` directly.

**Comment by ElTh0r0** [comment]
As mentioned in other discussions, I didn't follow any _strict_ convention which information is passed to `callCPU()` directly and what is available through the `game` object.

I intend to change the interface so that only the current board is exposed to `callCPU()`. All other information can be received by the CPU from the `game` object (if needed).

I'll add `game.getLastMove()` - it'll return array which contains the last move as [index from, number of stones, index to], if the player moved a tower. In any other case it'll return an empty array, as it is the easiest to implement from the existing code base 😌.
